### ISSUE TITLE
generated data and human evaluation result

### ISSUE THREAD

**Issue by seona0111** [microsoft/GODEL#14]
Hi.
I appreciate your model and codes.
But, I have interest in the dataset with human evaluation result.
If it is possible, could you share the generated dataset with human evaluation score.

**Comment by pengbaolin** [comment]
Thanks for your interests. I will discuss with the team on it and keep you posted.

**Comment by pengbaolin** [comment]
Hi @seona0111 , due to some legal concerns, we do not have any plan to publish the human evaluation scores.
