### ISSUE TITLE
Need test_file argument

### ISSUE THREAD

**Issue by drbrownman** [microsoft/GODEL#17]
When running train.py using train_file and validation_file arguments, get the following error.
```
Traceback (most recent call last):
  File "GODEL/train.py", line 633, in <module>
    main()
  File "GODEL/train.py", line 426, in main
    test_dataset = lm_datasets["test"]
  File "/GODEL/.py38venv/lib/python3.8/site-packages/datasets/dataset_dict.py", line 41, in __getitem__
    return super().__getitem__(k)
KeyError: 'test'
```

**Comment by pengbaolin** [comment]
Could you please share your cmd? I used the cmds in README and it works fine on my end.

**Comment by drbrownman** [comment]
Thanks Baolin.

Here is the command.
`python train.py --model_name_or_path ../models/GODEL-Base/ --train_file ../MBGodelData/history1/MBGodelData.train.json --validation_file ../MBGodelData/history1/MBGodelData.dev.json --test_file ../MBGodelData/history1/MBGodelData.test.json --output_dir ../models/MBDataModels/run5/ --exp_name godel2 --num_train_epochs 10 --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --max_target_length 32`

I am using a custom dataset. Since the issue was reported, we have modified the train.py file include a --test_file argument. PR #18 submitted.

**Comment by pengbaolin** [comment]
Thanks for your contribution, @drbrownman ! I have merged your PR.
