### ISSUE TITLE
Decoding Strategy? and Prompting Guide

### ISSUE THREAD

**Issue by ArEnSc** [microsoft/GODEL#25]
Did you guys use a specific decoding strategy other than beam search? and some values to reproduce the results ? In the paper you mentioned 5 beams.

Does this require few shot examples to produce coherant results, I am getting odd results either the knowledge is copied in the response or it generates unk |knowledge|> 

What is the strategy or template to prompt? I have read the paper it uses <|environment|> token between two exchanges of messages but
Reading the Server Code it looks like

context: "sentence. <|knowledge|>  knowledge sentence.  => "
generated:  "sentence. <|knowledge|>  knowledge sentence.  => generated sentence."

In the training data, one example for knowledge grounded looks like

START EOS:  

I am considering downloading the training data and seeing if I can see how it was trained to fix this issue but it seems like a lot of effort to get a demo working proper. 

It seems like the claims in the paper are that it does well in metrics, but there doesn't seem to be much discussion on how well it generates responses given knowledge grounded responses. Thanks

If you can provide an example of what 3 turns of knowledge grounded dialogue looks like and what 3 turns of no knowledge grounded dialogue looks like that would save an immense amount of time for people wanting to leverage this project.

@pengbaolin

**Comment by ArEnSc** [comment]
figured it out

**Comment by rivetchip** [comment]
> figured it out

Can you tell us how you did it ? I'm pretty sure other (including me) are interested :smiley:

**Comment by ArEnSc** [comment]
> > figured it out
> 
> @ArEnSc Can you tell us how you did it ? I'm pretty sure other (including me) are interested 😃

Okay so .... it didn't work, it generates random data ... I am wondering if the model is nurfed
