### ISSUE TITLE
Trained for longer? and using different prompt?

### ISSUE THREAD

**Issue by ArEnSc** [microsoft/GODEL#28]
@pengbaolin you mentioned for 1.1 you trained it for longer, is that dataset included and did you change the configuration for the training? It doesn't seem like you modified any of the code on the main branch for this

**Comment by AutomatonBloke** [comment]
I second this. Specifically how the "Instruction" segment fits in:

```
# Instruction for a chitchat task
instruction = f'Instruction: given a dialog context, you need to response empathically.'
```

I just recently looked into this model so I'm not sure if that segment of the training data is new or not compared to the current data format:

```
  {
    "Context": "Please remind me of calling to Jessie at 2PM.",
    "Knowledge": "reminder_contact_name is Jessie, reminder_time is 2PM",
    "Response": "Sure, set the reminder: call to Jesse at 2PM"
  },
```

**Comment by ArEnSc** [comment]
It also seems like it got instruct tuned.

**Comment by ArEnSc** [comment]
Don't think they are gonna respond
